# Site settings
email: leehydn@kaist.ac.kr

home:
  EN: Home
  日: ホーム
  한: 홈

portweb: 
  EN: devlog.ml
  日: devlog.ml
  한: ko.devlog.ml

title:
  EN: Hyeondong Lee
  日: Hyeondong Lee
  한: Hyeondong Lee
  CN: Hyeondong Lee

footTitle:
  EN: Thank you!
  日: ありがとうございます。
  CN: 您好！
  한: 안녕하세요!

contact:
  EN: Feel free to contact me!
  日: ご連絡はメールでお願いします。
  CN: 请通过电子邮件与我联系。谢谢。
  한: 기타 연락은 메일로 부탁드립니다.

weblink:
  EN: Blog
  日: 技術ブログ（英文）
  한: 블로그

description:
  EN: Hello! I am an undergraduate student from South Korea, studying computer science and mathematics. Thanks for your visit!.
  日: こんにちは！韓国のKAISTの電気電子工学部に所属している大学生です。立派な学者やエンジニアになるため日々邁進しています。失敗にも屈せず世界に役立てられるように頑張ります。
  CN: 我是一名学习电气工程和计算机的学生。
  한: 안녕하세요! 저의 블로그에 오신 것을 환영합니다.

defaults:
  -
    hidden: false

baseurl: "/" # the subpath of your site, e.g. /blog
url: "leehydn.github.io" # the base hostname & protocol for your site
twitter_username: leehydn
github_username:  leehydn
github_subname: naruei
linkedin_username:  leehydn

# Build settings
markdown: kramdown
