# Site settings
email: leehydn@kaist.ac.kr

home:
  EN: Home
  JA: ホーム
  KO: 홈

portweb: 
  EN: devlog.ml
  JA: devlog.ml
  KO: devcloud.tistory.com

title:
  EN: The Blog of Hyeondong Lee
  JA: Hyeondong Lee
  KO: Hyeondong Lee
  CN: Hyeondong Lee

footTitle:
  EN: Thank you!
  JA: ありがとうございます。
  CN: 您好！
  KO: 방문해 주셔서 감사합니다.

contact:
  EN: Feel free to contact me!
  JA: ご連絡はメールでお願いします。
  CN: 请通过电子邮件与我联系。谢谢。
  KO: 기타 연락은 메일로 부탁드립니다.

weblink:
  EN: Blog
  JA: 技術ブログ（英文）
  KO: 블로그

description:
  EN: Hello! I am an undergraduate student from South Korea, studying computer science and mathematics. Thanks for your visit!
  JA: こんにちは！韓国のKAISTの電気電子工学部に所属している大学生です。立派な学者やエンジニアになるためJA々邁進しています。失敗にも屈せず世界に役立てられるように頑張ります。
  CN: 我是一名学习电气工程和计算机的学生。
  KO: 안녕하세요. 여러분과 만나게 되어 반갑습니다.

index:
  EN: index
  JA: ja/index
  KO: ko/index

defaults:
  -
    hidden: false

baseurl: "/" # the subpath of your site, e.g. /blog
url: "leehydn.github.io" # the base hostname & protocol for your site
twitter_username: leehydn
github_username:  leehydn
github_subname: naruei
linkedin_username:  leehydn

# Build settings
markdown: kramdown
